# lightning.pytorch==2.0.0
seed_everything: 0
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: 'satclip'
  callbacks:
   - class_path: lightning.pytorch.callbacks.ModelCheckpoint
     init_args:
       monitor: "val_loss"
       dirpath: 'models/models-resnet-18-L-40'
       save_last: true
       filename: "{epoch}-{val_loss:.2f}"
  max_epochs: 500
  min_epochs: 100
  accelerator: 'gpu'
  devices:
    - 0
  num_sanity_val_steps: 0
model:
  embed_dim: 256
  image_resolution: 256
  vision_layers: 'moco_resnet18'
  vision_width: 128
  vision_patch_size: 32
  in_channels: 13
  le_type: 'sphericalharmonics'
  frequency_num: 32
  max_radius: 0.001
  min_radius: 0.00001
  legendre_polys: 40
  harmonics_calculation: 'analytic'
  sh_embedding_dims: 40
  pe_type: 'siren'
  learning_rate: 0.0001
  num_hidden_layers: 2
  capacity: 512
data:
  data_dir: '/scratch/WUR/ESG/russw001/S2-100k'
  batch_size: 512
  num_workers: 24
  val_random_split_fraction: 0.1
  transform: 'pretrained'
watchmodel: false